FROM node:20-alpine AS deps
WORKDIR /app
COPY package.json ./
COPY apps/web/package.json apps/web/package.json
RUN npm install
COPY . .
RUN npm -w apps/web run build

FROM node:20-alpine
WORKDIR /app
ENV NODE_ENV=production
COPY --from=deps /app/node_modules ./node_modules
COPY --from=deps /app/apps/web/package.json ./apps/web/package.json
COPY --from=deps /app/apps/web/.next ./apps/web/.next
COPY --from=deps /app/apps/web/public ./apps/web/public
COPY --from=deps /app/apps/web/next.config.js ./apps/web/next.config.js
CMD ["npm", "-w", "apps/web", "run", "start"]
